### ISSUE TITLE
Loader (winmm.dll) file size can be reduced

### ISSUE THREAD

**Issue by BlueberryWolf** [NotNite/GDWeave#15]
By using some rust compiler flags, and packing the loader with [UPX](https://github.com/upx/upx/), I managed to reduce the file size to 514kb (from 2MB)

UPX compresses your binary, and can be unpacked, and is therefore non-destructive

I did not thoroughly research the compiler flags I used, and therefore use them with caution.
```toml
[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
```

I found this convenient info from the following guide:
[min-sized-rust](https://github.com/johnthagen/min-sized-rust)

**Comment by BlueberryWolf** [comment]
It may not be the best solution to the issue (if it can even be considered one), but it is nice to see a smaller file size for the loader dll.

**Comment by BlueberryWolf** [comment]
To compress the binary, I used the following command:
```bat
upx --best --lzma loader.dll
```

cargo bloat reports the following:
![image](https://github.com/user-attachments/assets/b233f8ef-85d5-45c6-846f-04cc7e0de907)

**Comment by NotNite** [comment]
I am not stripping the binary, making panic abort, or using UPX, but I'd be willing to try the other things. UPX as a packer tends to set off antimalware.

**Comment by NotNite** [comment]
LTO only shaves ~500kb off of the DLL, which isn't worth it for the risk of unknown compiler flags, so I probably won't do this.
