### ISSUE TITLE
Replacing a pck file

### ISSUE THREAD

**Issue by keetsta** [NotNite/GDWeave#18]
Replacing a pck file with custom build / original game builded using gdre tools ending up with GDWeave not working, is there a way to fix this or is it a GDWeave problem?

**Comment by NotNite** [comment]
Do you mean loading a mod's custom pck file? What game and engine version?

**Comment by keetsta** [comment]
> Do you mean loading a mod's custom pck file? What game and engine version?

yes, the game version was 1.08 and the engine is GodotSteam 3.5.2
West merged pck and exe in one file so don't really know if loader will work with builded exe, i'll test it and write if it's not
