### ISSUE TITLE
Uninstalling GDWeave Locks My Vanilla WEBFISHING Avatar Into a Limbo State

### ISSUE THREAD

**Issue by KidnapperProot** [NotNite/GDWeave#19]
This is save-file bound mind you, but when I uninstall GDWeave; I am unable to change out of the default cat avatar. I can't change my species, face, clothing, nothing. The only was to fix this is to revert back to a version of my save file that was unaffected by GDWeave, and that's not optimal since I want to play modded, but also not be bound purely to modded.

My save file is like, super late-game, and almost the entirety of my journal is complete. I REALLY don't want to restart over an avatar softlock caused by a mod.

**Comment by NotNite** [comment]
GDWeave is a game-agnostic mod loader, not a WEBFISHING specific one. There is no code in GDWeave that touches your save file. You installed a mod that modified your save file. Please do not leave issues on the GDWeave repository unless they are actually related to the core mod loading components.
