### ISSUE TITLE
GDWeave no longer loads mods

### ISSUE THREAD

**Issue by MissingNO123** [NotNite/GDWeave#26]
The last two updates no longer load any mods in WEBFISHING. Downgrading to the second last version ([v2.0.12](https://github.com/NotNite/GDWeave/releases/tag/v2.0.12)) makes it suddenly work again. I have no more info to provide because there is no GDWeave.log file provided when this happens.

**Comment by NotNite** [comment]
My immediate guess is that the proxy DLL isn't being loaded at all. I'll have to look into this, I can't reproduce for now.

**Comment by MissingNO123** [comment]
As of WEBFISHING V1.10 everything mysteriously loads with no complications.
