### ISSUE TITLE
unsolvable crash

### ISSUE THREAD

**Issue by Atomlxe** [NotNite/GDWeave#35]
every time i try to launch webfishing i get the error "GDWeave failed to start: HostingError(InvalidConfigFile)" and i have no idea what could be causing it as ive just set up modded webfishing for the first time. it still happens with every mod disabled, and when trying to launch directly from steam

**Comment by NotNite** [comment]
GDWeave is not installed correctly or missing. Closing as this isn't a bug.

**Comment by Atomlxe** [comment]
> GDWeave is not installed correctly or missing. Closing as this isn't a bug.

except i have tried installing it multiple times, manually and through thunderstore, and complete reinstalls of the game, and i am still having the same issue.
