### ISSUE TITLE
GDWeave failed to start | HostingError Invalid config file

### ISSUE THREAD

**Issue by Mr-Atoms** [NotNite/GDWeave#36]
This is happening on the latest version, 2.0.14
![screenie](https://github.com/user-attachments/assets/ca35ab9a-8159-47f7-b2d5-db29c3817da4)
Closing it starts the game normally without GDweave.

**Comment by NotNite** [comment]
GDWeave is not installed correctly, this is not a bug. It's possible your antivirus deleted some files, perhaps.
