### ISSUE TITLE
Failed to start: HostingError(InvalidConfigFile)

### ISSUE THREAD

**Issue by Alexasha05** [NotNite/GDWeave#37]
Hey there! Was playing with this mod on dec 31st and it was working just fine, after launching the game today started getting the following error:
![Screenshot_1](https://github.com/user-attachments/assets/6cbc1b6b-0c66-470e-9a04-b426b8c7933a)
Tried reinstalling, didn't help. Doesn't work when launching via both r2modman and w/o it. The only difference I noticed between launching manually and using r2mm is that r2mm doesn't even give me the error window and instantly closes the game while opening the game manually gives out the error from the attached image. What could I do to fix that? Launching the vanilla game via r2modman works perfectly fine too. Here's the log.
[GDWeave.log](https://github.com/user-attachments/files/18283989/GDWeave.log)

**Comment by NotNite** [comment]
GDWeave is missing or corrupted, possibly because an antivirus deleted something. Reinstall it.

**Comment by Alexasha05** [comment]
Turned off the antivirus, did a complete reinstallation of both the game and r2modman (made sure to clear the cache too), the error still wouldn't get solved.

https://github.com/user-attachments/assets/918e758e-7a24-4bff-8008-4b78ebb0473c

Here's a video on me turning off the antivirus and launching the game both via the launcher and manually. Tried launching it without the Lure mod, no difference.

**Comment by Alexasha05** [comment]
Forgot to mention something - I also tried manually installing the mod (w/o the help of r2mm) before reinstalling the game completely - got the same error.

**Comment by digimacska17** [comment]
Same for me yesterday worked, probably the new update has to do with that problem.

**Comment by SAWSYSTEM** [comment]
anyone got a fix atp? my thread was closed and i was sent here with no actual help. i've reinstalled GDWeave a few times and nothing has changed.
